FUND_ADDRESS = "3D3J5tQ5trfZnzDwSozgCTY73PmfuybSuj"
TX_API_URL = "https://mempool.space/api/address"
HISTORICAL_PRICE_API_URL = "https://mempool.space/api/v1/historical-price"
LIVE_PRICE_API_URL = "https://mempool.space/api/v1/prices"
TX_STORAGE = "transactions.db"
PRICE_STORAGE = "prices.db"